/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MediumRouteImport } from './routes/medium'
import { Route as LightRouteImport } from './routes/light'
import { Route as HeavyRouteImport } from './routes/heavy'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'

const MediumRoute = MediumRouteImport.update({
  id: '/medium',
  path: '/medium',
  getParentRoute: () => rootRouteImport,
} as any)
const LightRoute = LightRouteImport.update({
  id: '/light',
  path: '/light',
  getParentRoute: () => rootRouteImport,
} as any)
const HeavyRoute = HeavyRouteImport.update({
  id: '/heavy',
  path: '/heavy',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/heavy': typeof HeavyRoute
  '/light': typeof LightRoute
  '/medium': typeof MediumRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/heavy': typeof HeavyRoute
  '/light': typeof LightRoute
  '/medium': typeof MediumRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/heavy': typeof HeavyRoute
  '/light': typeof LightRoute
  '/medium': typeof MediumRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/heavy' | '/light' | '/medium'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/heavy' | '/light' | '/medium'
  id: '__root__' | '/' | '/auth' | '/heavy' | '/light' | '/medium'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  HeavyRoute: typeof HeavyRoute
  LightRoute: typeof LightRoute
  MediumRoute: typeof MediumRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/medium': {
      id: '/medium'
      path: '/medium'
      fullPath: '/medium'
      preLoaderRoute: typeof MediumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/light': {
      id: '/light'
      path: '/light'
      fullPath: '/light'
      preLoaderRoute: typeof LightRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heavy': {
      id: '/heavy'
      path: '/heavy'
      fullPath: '/heavy'
      preLoaderRoute: typeof HeavyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  HeavyRoute: HeavyRoute,
  LightRoute: LightRoute,
  MediumRoute: MediumRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
